"""
Django settings for freedomwoods project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root if present (for EMAIL_* and other secrets on server).
try:
    from dotenv import load_dotenv
    _env_file = BASE_DIR / ".env"
    if _env_file.exists():
        load_dotenv(_env_file)
    else:
        # Fallback: try cwd (e.g. if server runs from project root)
        load_dotenv()
except ImportError:
    pass

# Path for auto-generated secret key (created on first run if no env var set).
SECRET_KEY_FILE = BASE_DIR / ".secret_key"


def _get_secret_key():
    """Use DJANGO_SECRET_KEY env, or .secret_key file, or generate and persist one."""
    key = os.environ.get("DJANGO_SECRET_KEY", "").strip()
    if key:
        return key
    if SECRET_KEY_FILE.exists():
        return SECRET_KEY_FILE.read_text().strip()
    # Generate a new key and save it (no env vars needed on server)
    try:
        import secrets
        key = secrets.token_urlsafe(50)
    except ImportError:
        import random
        import base64
        key = base64.urlsafe_b64encode(
            bytes(random.getrandbits(8) for _ in range(48))
        ).decode().rstrip("=")
    try:
        SECRET_KEY_FILE.write_text(key)
        SECRET_KEY_FILE.chmod(0o600)
    except OSError:
        pass
    return key


# -----------------------------------------------------------------------------
# Environment-based configuration (optional; defaults work for production)
# -----------------------------------------------------------------------------
SECRET_KEY = _get_secret_key()

# Default DEBUG=0 (production). Set DJANGO_DEBUG=1 for local development.
DEBUG = os.environ.get("DJANGO_DEBUG", "0").strip().lower() in ("1", "true", "yes")

_raw_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _raw_hosts.split(",") if h.strip()]
    if _raw_hosts
    else ["home.freedomwoods.online", "localhost", "127.0.0.1"]
)

_raw_origins = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "https://home.freedomwoods.online")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_origins.split(",") if o.strip()]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',
    'tickets',
    'dataanalysis',
    'crispy_forms',
    'crispy_bootstrap5',
]
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'freedomwoods.middleware.NoCacheHtmlMiddleware',
]

ROOT_URLCONF = 'freedomwoods.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pages.context_processors.nav_apps',
                'pages.context_processors.static_version',
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# Production security (when DEBUG is False)
# -----------------------------------------------------------------------------
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Default 0 when behind Cloudflare/tunnel (they do HTTPS). Set to 1 if Django is the TLS terminator.
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "0") in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

WSGI_APPLICATION = 'freedomwoods.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Detroit'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# WhiteNoise: in production, serve static files and use hashed names for cache busting
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Bump this on deploy to force browsers to load new CSS/JS (avoids cache)
STATIC_VERSION = '2.1'

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# -----------------------------------------------------------------------------
# Email (contact form → Gmail). Set in env: EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, CONTACT_EMAIL
# For Gmail use an App Password: https://myaccount.google.com/apppasswords
# -----------------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
CONTACT_EMAIL = os.environ.get("CONTACT_EMAIL", EMAIL_HOST_USER)  # Where contact form submissions go
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@freedomwoods.online"

# -----------------------------------------------------------------------------
# Logging (production: errors to file; development: console)
# -----------------------------------------------------------------------------
LOG_DIR = BASE_DIR / "log"
if not DEBUG and not LOG_DIR.exists():
    try:
        LOG_DIR.mkdir(parents=False, exist_ok=True)
    except OSError:
        LOG_DIR = None

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

if not DEBUG and LOG_DIR:
    LOGGING["handlers"]["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": LOG_DIR / "django.log",
        "maxBytes": 1024 * 1024 * 5,
        "backupCount": 3,
        "formatter": "verbose",
    }
    LOGGING["root"]["handlers"].append("file")
    LOGGING["loggers"] = {
        "django.request": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
    }