# Generated by Django 5.2.7 on 2026-02-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('parquet', 'Parquet')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dataanalysis.datasets')),
            ],
        ),
    ]
