# Generated by Django 5.2.7 on 2026-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0003_add_manual_record_and_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('mpx', 'MPX'), ('mpx_dek', 'MPX.DEK'), ('parquet', 'Parquet')], max_length=10),
        ),
    ]
